services:

# BASE DE DATOS MYSQL
  db:
    image: mysql:8.0
    container_name: lamp_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mi_basetrfgggggggg52
      MYSQL_USER: usuario
      MYSQL_PASSWORD: password123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - lamp_network

# SERVIDOR APACHE CON PHP
  web:
    build: .
    container_name: lamp_web
    restart: always
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - lamp_network

networks:
  lamp_network:
    driver: bridge
  
volumes:
  db_data: